### ISSUE TITLE
US12 - Filtrar Processo individualmente e por Fluxo

### ISSUE THREAD

**Issue by M0tt1nh4** [fga-eps-mds/2023-2-CAPJu-Doc#10]
## Descrição da História
Eu, como estagiário, servidor, diretor, juiz, e administrador, gostaria de filtrar os processos por meio dos Fluxos para poder visualizar quais processos fazem parte do mesmo Fluxo.

## Tasks
As seguintes tasks, devem ser completadas para concluir a história:   
- [ ] [Filtrar os processos exibindo apenas os que estão dentro de um fluxo](https://github.com/fga-eps-mds/)

## Critérios de Aceitação
- [x] Poder visualizar um campo de busca com seleções.
- [x] Ao clicar no filtro escolhido, poder ver, entre as opções, "Fluxo"
- [x] Poder selecionar uma das opções e fazer uma busca a partir dela
- [x] Obter o resultado de quais processos estão em determinado Fluxo

![img2](https://media.discordapp.net/attachments/1144345999553351710/1172282281784778893/image.png?ex=655fbff3&is=654d4af3&hm=4c4a737856f60885bce03b3cda05b29d61ad185f62b62e15843f82cc24609897&=&width=938&height=618)

![img1](https://media.discordapp.net/attachments/1144345999553351710/1172282030722121748/image.png?ex=655fbfb8&is=654d4ab8&hm=648214a10838d58c079978b97a84d60537f6230e93a42d5aaa870021ebe7eb2e&=&width=938&height=618)

**Comment by well1981** [comment]
- mesma observação da US 11 (está US faz sentido)

**Comment by well1981** [comment]
Novos critérios de aceitação validados.

**Comment by well1981** [comment]
O sistema não pesquisa quando digita o termo de pesquisa e depois altera o critério de pesquisa. Favor ajustar, inclusive, se possível, que a busca desconsidere letras maiúsculas e minúsculas, bem como caracteres especiais.

**Comment by well1981** [comment]
Validada a implementação.
