### ISSUE TITLE
US13 - Visualizar Processos na Etapa de um Fluxo

### ISSUE THREAD

**Issue by M0tt1nh4** [fga-eps-mds/2023-2-CAPJu-Doc#11]
## Descrição da História
Eu, como estagiário, servidor, diretor, juiz, e administrador, gostaria de visualizar os processos na etapa de um fluxo para poder acessar quais processos se encontram em determinada etapa de um fluxo.

## Tasks
As seguintes tasks, devem ser completadas para concluir a história:   
- [ ] Filtrar os processos de uma etapa dentro de um fluxo

## Critérios de Aceitação
- [ ] Conseguir filtrar processos de qualquer etapa dentro de qualquer fluxo
- [ ] Os processos filtrados estarem corretos
- [ ] A quantidade exibida de processos estar correta

![Frame 1](https://media.discordapp.net/attachments/750707734910992535/1162121436379484261/Estatisticas.png?ex=653ac8ed&is=652853ed&hm=1fadc3a45af7291836a144926a794c7f387570634351d0dee83ce5a3c2b1edd5&=&width=874&height=616)
![Frame 2](https://media.discordapp.net/attachments/750707734910992535/1162121437037985923/Estatisticas_1.png?ex=653ac8ed&is=652853ed&hm=539ad3ea8923905534dedb3b877fe0785fe52b6ebb9c97568f49facbcb40c814&=&width=874&height=616)
![Frame 3](https://media.discordapp.net/attachments/750707734910992535/1162121437390323843/Estatisticas_2.png?ex=653ac8ed&is=652853ed&hm=eb40084b5af2eac7c86efb999369f84dcb8436d3dedc3a1c9554753a73807c27&=&width=874&height=616)

**Comment by JongaMatos** [comment]
Esta issue foi agregada à US01
