### ISSUE TITLE
US07 - Importação automática de processos em xlsx

### ISSUE THREAD

**Issue by Denniel-sudo** [fga-eps-mds/2023-2-CAPJu-Doc#12]
## Descrição da História
Eu, como servidor, diretor ou administrador gostaria de importar automaticamente os processos através de um arquivo xlsx para poder realizar a importação de forma mais prática.

## Tasks
- [ ] Definir formato template de pdf a ser aceito
- [ ] Criar protótipo
- [ ] Definir estrutura a ser enviada ao back-end
- [ ] Construção front-end
- [ ] Construção back-end

## Critérios de Aceitação
- [x] Poder visualizar o botão de visualização de lote e acioná-lo
- [x] Poder acionar o botão de importação
- [x] Poder dar um nome à importação que será realizada
- [x] Poder selecionar um arquivo (ou mais) no formato xlsx
- [x] Visualizar processos importados na página sem perda de informação

![image](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/assets/48032705/013b56fe-1a12-48df-b132-09fc52c1c915)
![img2](https://media.discordapp.net/attachments/750707734910992535/1169638485712449606/image.png?ex=655621b9&is=6543acb9&hm=e03515ee5e4963836deec969dd7392028fc7430cc9817c97b41efd32de3b1a71&=&width=818&height=579)
![image](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/assets/48032705/398fc4b4-da26-4679-a239-8b7158591c7d)

**Comment by well1981** [comment]
- na "Descrição da História" consta "arquivo pdf", mas o correto é "arquivo xlsx"
- na primeira tela alterar o nome do botão de "visualizar lotes" para "+ Importar Processos"
- o botão "baixar modelo" ficaria melhor na segunda tela ao lado do botão "importar lote"

**Comment by brendavsantos** [comment]
Sobre os pontos, de forma respectiva:

1 - Feito, a descrição foi ajustada!
2 - Não acho que faça sentido mudar, ao clicar no botão o usuário será levado à visualização dos lotes, e não para a importação de arquivos. A importação só será feita a partir do botão de importar.
3 - Bem observado, concordamos e já alteramos!

**Comment by well1981** [comment]
Item 2: o termo "lotes" não é comum no judiciário, mas "importação" sim; mantenho a observação.

**Comment by well1981** [comment]
Na validação dos critérios de aceitação, indico as seguintes pendências:
- modelo não baixa, conforme o seguinte erro:
![image](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/assets/121133676/8616a54c-eaac-4d64-9e19-5533ab95421a)
- não consegui verificar critério "Visualizar processos importados na página sem perda de informação" por conta da demanda acima

**Comment by well1981** [comment]
Validada a implementação.
