### ISSUE TITLE
US16 - Agrupamento de funcionalidades

### ISSUE THREAD

**Issue by JongaMatos** [fga-eps-mds/2023-2-CAPJu-Doc#13]
## **Descrição da história**

Eu, como usuário, gostaria de visualizar as funcionalidades do sistema agrupadas de forma intuitiva, para conseguir navegar pela interface de forma fácil e eficiente.

## **Tasks**

As seguintes tasks devem ser completas para concluir a história:

- [x] Visualizar o botão de ícone de perfil e poder acioná-lo.
- [x] Ao acionar o botão de ícone de perfil, as seguintes opções devem ser visualizadas: "Cadastro", "Perfis e Permissões", "Editar conta", "Sobre" e "Sair".
- [x] Ao clicar em qualquer opção do botão de ícone de perfil, o usuário deve ser redirecionado para as páginas correspondentes.
- [x] Na página "Editar conta" deverá ser possível alterar as informações da conta.
- [x] Ao alterar qualquer informação da conta, o usuário deve ser redirecionado para a página de login.

Alterações propostas: 
- Agrupamento de Perfis e permissões, editar conta, sobre e sair tudo em um menu só
- Alteração do nome da aba de cadastro para "solicitações de cadastro" (não tem a ver com agrupamento mas é melhoria de ux)
- Agrupamento das funcionalidades de editar email e editar senha em uma tela só de edição de conta
- Adição do menu no cabeçalho da página com pequenas modificações para sinalizar em qual aba o usuário está
- Diminuição do campo de busca e alteração da localização do botão de criar (seja fluxo, processo, unidade etc)

![image](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/assets/48032705/4f76723f-1118-4a03-af7e-cb6679ef8ece)

![image](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/assets/48032705/4c7a2af7-b221-483b-97d0-2849f8088873)

![image](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/assets/48032705/8e760a57-c542-4c77-9592-84112ce21b53)

**Comment by well1981** [comment]
Validados os critérios de aceitação e a implementação.
