### ISSUE TITLE
US01 - Visualizar quantidade de processos em cada etapa de um fluxo

### ISSUE THREAD

**Issue by DanielRogs** [fga-eps-mds/2023-2-CAPJu-Doc#14]
## Descrição da História
Eu, como usuário, gostaria de poder visualizar a quantidade de processos em cada etapa de um fluxo selecionado para poder ter uma visão clara dos gargalos em cada etapa, atrasos ou áreas do processo que precisam de atenção especial.

## Tasks
As seguintes tasks  devem ser completas para concluir a história:
- [x] Criação de protótipo
- [ ] Criar/Verificar informações ausentes no banco
- [ ] Implementar os dados estatísticos em um gráfico.

## Critérios de Aceitação
Seção para os critérios que definem acerca da aceitação da tarefa. 
- [x] Visualizar a quantidade de processos por etapa de um fluxo
- [x] Poder ver o campo de seleção e escolher qual o fluxo que se deseja ver as etapas
- [x] Visualizar se o gráfico contém as etapas corretas do fluxo escolhido
- [x] Poder ver o campo de seleção e escolher entre as etapas do fluxo escolhido a que se deseja ver os processos
- [x] Poder ver os processos filtrados por etapa
- [x] Analisar se os processos mostrados são da etapa escolhida

## Capturas de Telas (Protótipo)
![imagem](https://media.discordapp.net/attachments/750707734910992535/1162135826466082876/EstatisticasSugestao-1.png?ex=653ad654&is=65286154&hm=78b7177cbc8f59acd20e0836690f3c2c07f3f06ce8665907269ed0eac893fdb9&=&width=874&height=616)
![imagem](https://media.discordapp.net/attachments/750707734910992535/1162135826805829793/EstatisticasSugestao.png?ex=653ad654&is=65286154&hm=e03b441537ea278ecd8626be0a89cfe9336cd9a5167e4dfd318c063ddb2f2688&=&width=874&height=616)
![imagem](https://media.discordapp.net/attachments/750707734910992535/1162135825992142888/EstatisticasSugestao-2.png?ex=653ad654&is=65286154&hm=784d69f5abefb40f63381f4014e8e9ee6e3089fd22d6428de7a0ca6ce0329e20&=&width=874&height=616)

**Comment by well1981** [comment]
Está correto agora. Pode prosseguir.

**Comment by well1981** [comment]
- não consegui visualizar o nome dos botões azuis; cliquei no que fica na primeira tela e funcionou (baixou o gráfico em PDF);
- cliquei no primeiro da segunda tela e funcionou (baixou lista de processos em Excel);
- cliquei no segundo da segunda tela e não funcionou; 
- a planilha precisa ser configurada (a única informação clara é o número do processo)
- achei estranho a estatística mostrar processos na aba processos não ter nenhum cadastrado
- a lista de processos mostrou apenas 3 processos na primeira página: esse será o padrão?

**Comment by well1981** [comment]
Mensagem anterior: botões de download são da US05.
Validação da implentação (pendências):
- mensagem que aparece ao posicionar o mouse sobre o gráfico: trocar "Etapas:" por "Processos:"
- manter a informação do fluxo selecionado e colocar ao lado a opção de "selecione a etapa"

**Comment by well1981** [comment]
> Mensagem anterior: botões de download são da US05. Validação da implentação (pendências):
> 
> * mensagem que aparece ao posicionar o mouse sobre o gráfico: trocar "Etapas:" por "Processos:"
> * manter a informação do fluxo selecionado e colocar ao lado a opção de "selecione a etapa"
> * falta mensagem de erro ao clicar em confirmar sem selecionar a etapa

Itens 1 e 2 resolvidos e item 3 na US015.
