### ISSUE TITLE
US20 - Deslogar depois de determinado tempo de inatividade

### ISSUE THREAD

**Issue by brendavsantos** [fga-eps-mds/2023-2-CAPJu-Doc#15]
## Descrição da História
Eu, como usuário, gostaria de ser deslogado depois de determinado tempo de inatividade para poder evitar acessos de usuários indesejados.

## Tasks
As seguintes tasks  devem ser completas para concluir a história:
- [x] [Definir tempo máximo de inatividade antes do bloqueio](https://github.com/fga-eps-mds/)
- [x] [Iniciar a contagem de tempo de inatividade](https://github.com/fga-eps-mds/)
- [x] [Quando o tempo for excedido, fazer o logout do usuário](https://github.com/fga-eps-mds/)

## Critérios de Aceitação
Seção para os critérios que definem acerca da aceitação da tarefa. 
- [x] O usuário receberá um aviso de quanto tempo falta para a sessão expirar
- [x] O usuário deverá ter seu login encerrado e ser direcionado à pagina de login após 5 minutos no software;
- [x] Deverá aparecer um aviso de tempo excedido após ser deslogado.

Imagem do aviso funcionando em tempo real 
![tela](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/assets/48032705/ec122a10-0bdd-4be5-b244-2ff901977584)
)

**Comment by well1981** [comment]
Validada a implementação.
