### ISSUE TITLE
US17 - Fluxo de Exibição de Telas

### ISSUE THREAD

**Issue by JongaMatos** [fga-eps-mds/2023-2-CAPJu-Doc#16]
## **Descrição da história**

Eu, como usuário, gostaria de navegar pela interface do sistema de forma fluida e intuitiva, para conseguir utilizar o sistema com facilidade.

## **Tasks**

As seguintes tasks devem ser completas para concluir a história:

- [x] Criar protótipo com proposta de alteração no fluxo de exibição de telas.
- [x] Validar protótipo com o cliente.
- [x] Fazer ajustes no protótipo (caso o cliente solicite).
- [x] Implementar alterações conforme protótipo validado.

![image](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/assets/48032705/e786f016-1ae4-42ab-9fbe-482f30c2bad9)
![image](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/assets/48032705/00617f5f-3411-4f29-93da-7f634b67dcf8)

![image](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/assets/48032705/10869cf3-aac3-485b-81ba-26304d5404d5)
![image](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/assets/48032705/d065b808-e78b-4d70-aaf1-8821103d1e00)

**Comment by well1981** [comment]
Validados os critérios de aceitação em reunião, bem como a implementação parcial da US, tendo em vista a seguinte observação:
_US17: ao clicar na aba processos e no ícone visualizar (olhinho) o sistema deveria abrir uma nova tela sobreposta e não redirecionar para outra tela; não teve tempo hábil para essa alteração._

**Comment by brendavsantos** [comment]
Modificações a serem realizadas depois:

 ![image](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/assets/48032705/10869cf3-aac3-485b-81ba-26304d5404d5)
 ![image](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/assets/48032705/d065b808-e78b-4d70-aaf1-8821103d1e00)
