### ISSUE TITLE
US08 - Importação automática de processos em CSV

### ISSUE THREAD

**Issue by Denniel-sudo** [fga-eps-mds/2023-2-CAPJu-Doc#17]
## Descrição da História
Eu, como servidor, diretor ou administrador gostaria de importar automaticamente os processos através de um arquivo csv  para poder realizar a importação de forma mais prática.

## Tasks
- [ ] Definir formato template de pdf a ser aceito
- [ ] Criar protótipo
- [ ] Definir estrutura a ser enviada ao back-end
- [ ] Construção front-end
- [ ] Construção back-end

## Critérios de Aceitação
- [x] Poder visualizar o botão de visualização de lote e acioná-lo
- [x] Poder acionar o botão de importação
- [x] Poder dar um nome à importação que será realizada
- [x] Poder selecionar um arquivo (ou mais) no formato cvs
- [ ] Visualizar processos importados na página sem perda de informação

![image](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/assets/48032705/013b56fe-1a12-48df-b132-09fc52c1c915)
![img2](https://media.discordapp.net/attachments/750707734910992535/1169638485712449606/image.png?ex=655621b9&is=6543acb9&hm=e03515ee5e4963836deec969dd7392028fc7430cc9817c97b41efd32de3b1a71&=&width=818&height=579)
![image](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/assets/48032705/398fc4b4-da26-4679-a239-8b7158591c7d)

**Comment by well1981** [comment]
- mesmas observações da US07

**Comment by well1981** [comment]
Validação dos critérios de aceitação: ver observações da US07.

**Comment by well1981** [comment]
Validada a implementação.
