### ISSUE TITLE
US09 - Atualização e visualização de status do processo

### ISSUE THREAD

**Issue by Denniel-sudo** [fga-eps-mds/2023-2-CAPJu-Doc#19]
## Descrição da História
Eu, como servidor, diretor ou administrador gostaria de atualizar e visualizar o status de um processo para poder acompanhar a situação do processo.

## Tasks
- [x] Modificar o backend para atualizar o status do processo ao clicar no botão
- [x] Trocar nomenclatura do status e botão "Finalizar Processo" para "Concluir Processo"
- [x] Trocar nomenclatura do status e botão "Arquivar Processo" para "Interromper Processo"
- [x] Trocar nomenclatura do botão "Desarquivar processo" para "Reativar Processo"

## Critérios de Aceitação
- [x] Ao clicar no botão "Interromper Processo" espera-se que o status do processo mude para "Interrompido"
- [x] Ao clicar no botão "Concluir Processo" espera-se que o status do processo mude para "Concluído" 
- [x] Ao clicar no botão "Reativar processo" espera-se que o status do processo mude para "Em andamento"

**Conseguir visualizar todos os tipos de status dos processos**
**Na tabela dentro da página dos processos:**
   - [x] O processo no status "Não Iniciado";
   - [x] O processo no status "Em Andamento";
   - [x] O processo no status "Interrompido";
   - [x] O processo no status "Concluído".
 
**Na informação "status" dentro da página detalhada do processo selecionado:**
   - [x] O processo no status "Não Iniciado";
   - [x] O processo no status "Em Andamento";
   - [x] O processo no status "Interrompido";
   - [x] O processo no status "Concluído".

**Na página de Processos:**
![img1](https://i.imgur.com/juZGLPg.png)

**Na página da informação do processo quando ele está em andamento:**
![img2](https://i.imgur.com/0mpSZEY.png)

**Na página da informação do processo quando ele está na última etapa:**
![img3](https://i.imgur.com/Zer0NTd.png)

**Na página da informação do processo quando ele está interrompido:**
![img4](https://i.imgur.com/jDle2GK.png)

**Comment by LeanArs** [comment]
@well1981 , ao verificarmos a regra de negócio do sistema, notamos que, diferente do que conversamos na reunião do dia 30/10/2023, "finalizar processo" se referia ao processo que percorreu todas as etapas. E "arquivar processo" se referia ao processo que por algum motivo extraordinário travou. De tal forma, adaptamos o protótipo para corresponder melhor o que conversavámos durante a reunião. Por favor, caso encontre qualquer divergência de ideias nos comunique sem pensar duas vezes.

**Comment by well1981** [comment]
- não entendi o critério de aceitação "O processo estar no status correspondente à ação tomada"
- na segunda tela, não existe o status "em progresso" (o correto é "em andamento)
- alterar o nome de "retroceder de etapa" para "retroceder etapa"
- alterar o nome "retomar processo" para "reativar processo"

**Comment by DanielRogs** [comment]
Olá @well1981! Fizemos as correções que você solicitou, pode avaliar para nós?

**Comment by well1981** [comment]
Excelente os ajustes!

**Comment by well1981** [comment]
Válido a implementação.
