### ISSUE TITLE
US14 - Visualizar Relatório de Processos pela Data de Vencimento de uma Etapa

### ISSUE THREAD

**Issue by M0tt1nh4** [fga-eps-mds/2023-2-CAPJu-Doc#20]
## Descrição da História
Eu, como estagiário, servidor, diretor, juiz, e administrador, gostaria de visualizar um relatório de processos filtrados pela data de vencimento para poder visualizar todos que vencem até determinada data.

## Tasks
As seguintes tasks, devem ser completadas para concluir a história: 
- [x] Filtrar uma etapa pela sua data de vencimento
- [ ] Gerar um relatório dos processos da etapa filtrada

## Critérios de Aceitação
Seção para os critérios que definem acerca do funcionamento da tarefa.
- [x] Poder expandir campo de "visualizar processos pela data de vencimento de uma etapa" na aba de estatísticas
- [x] Poder visualizar e preencher/selecionar os campos de data inicial e final do filtro
- [x] Após contifmar as datas escolhidas, poder confirmar e ver os processos listados
- [x] Confirmar que os processos listados foram filtrados corretamente, a data de vencimento da etapa realmente vence no período escolhido

###### Etapa 1 (US refere-se ao quarto tópico das estatísticas):
![Frame](https://imgur.com/bujyJHv.png)

###### Etapa 2:
![Frame 1](https://imgur.com/DTEsrEF.png)

###### Etapa 3:
![Frame 2](https://imgur.com/1K47QbT.png)

## Link do Figma:

https://www.figma.com/file/YocYFs8VfMDFFk1hWNwLQv/CAPJu?type=design&node-id=179%3A3458&mode=design&t=ZOFv3oQ4LuY46Med-1

**Comment by well1981** [comment]
Está correto. Pode prosseguir.

**Comment by well1981** [comment]
O relatório parece estar funcionado corretamente, mas não foi possível baixar o relatório em PDF e CSV, conforme comentário na US 05).

**Comment by well1981** [comment]
Validação da implentação (pendências):
- é preciso mostrar a data de vencimento na coluna
- ordenar os processos pela data de vencimento
- depois de visualizar um processo, manter a pesquisa feita com as atualizações necessárias (processo movimentado)

**Comment by well1981** [comment]
Trocar o texto da coluna "prazo da etapa" para "Data de vencimento da etapa".

**Comment by well1981** [comment]
Ver a possibilidade de travar o primeiro calendário para permitir selecionar a data inicial a partir apenas da data atual.

**Comment by well1981** [comment]
![image](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/assets/121133676/270bac90-1aff-4c57-9722-f8a848dd9bb4)

**Comment by well1981** [comment]
> Ver a possibilidade de travar o primeiro calendário para permitir selecionar a data inicial a partir apenas da data atual.

Implentação ok

**Comment by well1981** [comment]
> Trocar o texto da coluna "prazo da etapa" para "Data de vencimento da etapa".

Implentação ok

**Comment by well1981** [comment]
> ![image](https://private-user-images.githubusercontent.com/121133676/285324178-270bac90-1aff-4c57-9722-f8a848dd9bb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMzMxMTYsIm5iZiI6MTcwMTEzMjgxNiwicGF0aCI6Ii8xMjExMzM2NzYvMjg1MzI0MTc4LTI3MGJhYzkwLTFhZmYtNGM1Ny05NzIyLWY4YTg0OGRkOWJiNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOFQwMDUzMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzJhNGIyOWQzNzEzZjIwYzRkZGQyN2E2MjlkY2NiNGM1NDYwMDkwNTE0OGVlMDA2ZWFmODM2NjZjNzE1ZjZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Hs0RTd-e-qDE3sAQ_Yh3XH07VGjjy-n5fzsadEDsBeA)

Implentação ok
