### ISSUE TITLE
US06 - Visualizar o histórico das atividades dos processos

### ISSUE THREAD

**Issue by DaviRogs** [fga-eps-mds/2023-2-CAPJu-Doc#21]
## Descrição da História
Eu, como estagiário, servidor, diretor, juiz, e administrador, gostaria de visualizar o processo de forma detalhada e seus avanços de status no decorrer do tempo.

## Tasks

As seguintes tasks, devem ser realizadas para concluir a história: 

- [x] Alinhar e validar para saber quais dados de fato o mesmo deseja visualizar
- [x] Construir protótipo
- [x] Criar um espaço do histórico ao detalhar o processo
- [x] Possuir a data e hora do ocorrido
- [x] Histórico de ação com o responsável e tempo do ocorrido

* E deverá possuir os seguintes tipos de históricos:
 - [x] Início do processo
 - [x] Mudança de status do processo
 - [x] Finalização do processo
 
## Critérios de Aceitação
Seção para os critérios que definem acerca da aceitação da tarefa. 
- [x] Conseguir visualizar o campo onde é exibido o histórico com tipo certo de histórico e os campos corretos
- [x] No histórico visualizar um histórico de quem moveu, quando moveu, qual foi a movimentação feita e o tempo que demorou para essa ação acontecer (tempo que ficou retido na etapa)
- [x] No Histórico ver quando o processo for criado e quem criou.
- [x] No Histórico ver quando o processo for concluído, quem concluiu e quanto tempo demorou para ser concluído.
- [x] No Histórico ver quando o processo for Finalizado e quem finalizou e quanto tempo demorou para ser concluído.

## Capturas de Tela (Protótipo)

Página completa de informações do Processo:
![Frame 1](https://media.discordapp.net/attachments/750707734910992535/1162130003631284305/Processos_Pt.2_V2.png?ex=653ad0e8&is=65285be8&hm=16b41108f501f717dc33dbb8ff4f21563ac1413012eec2e798a1616abda788ef&=&width=419&height=616)

Somente o Histórico:
![Frame1](https://i.imgur.com/7mfd6KR.png)

**Comment by Denniel-sudo** [comment]
Alinhar com o Wellington qual a rastreabilidade? 
- Quando alguém alterar um fluxo, mostrar quem que alterou e quando? O mesmo para as etapas? Ou só mostrar mesmo quem fez a mudança de uma etapa e quando fez? (Ou os três).

**Comment by well1981** [comment]
> Alinhar com o Wellington qual a rastreabilidade?
> 
> * Quando alguém alterar um fluxo, mostrar quem que alterou e quando? O mesmo para as etapas? Ou só mostrar mesmo quem fez a mudança de uma etapa e quando fez? (Ou os três).

Na verdade, devem ser indicadas as mudanças efetuadas na movimentação do processo, que consequentemente são alterações nas etapas.

**Comment by well1981** [comment]
Está correto agora. Pode prosseguir.

**Comment by well1981** [comment]
Validada a implementação.
