### ISSUE TITLE
US02 - Estatística da quantidade de processos concluídos e interrompidos por fluxo

### ISSUE THREAD

**Issue by DanielRogs** [fga-eps-mds/2023-2-CAPJu-Doc#22]
## Descrição da História
Eu, como usuário, gostaria de ter a capacidade de visualizar um relatório que apresente todos os processos concluídos ou finalizados, podendo ser filtrado por fluxo, status e segmentado por período. Além disso, um gráfico que se adeque aos campos de filtro, segmentado por mês, para poder comparar a produtividade ao longo do tempo.

## Tasks
As seguintes tasks  devem ser completas para concluir a história:
- [x] Criação de protótipo;
- [x] Acrescentar o status dos processos no banco: Em Andamento, Interrompido e Concluído;
- [x] Validação da forma de amostragem dos dados;
- [x] Implementação do relatório na página "Estatísticas";
- [x] Implementação do gráfico na página "Estatísticas"

## Critérios de Aceitação
Seção para os critérios que definem acerca da aceitação da tarefa. 
- [x] Poder expandir o campo de estatísticas com nome "Visualizar quantidade de processos concluídos / interrompidos"
- [x] Visualizar o relatório geral ao expandir o campo de estatísticas
- [x] Poder visualizar a quantidade total de processos, de acordo com os filtros (caso não tenha filtro, mostrar de quantidade geral)
- [x] Poder visualizar a quantidade total de processos concluídos, de acordo com os filtros (caso não tenha filtro, mostrar de quantidade geral)
- [x] Poder visualizar a quantidade total de processos interrompidos, de acordo com os filtros (caso não tenha filtro, mostrar de quantidade geral)
- [x] Poder realizar um filtro no relatório por fluxo, status e ou período (data x à data y)
- [x] Poder visualizar corretamente os relatórios filtrados
- [x] Ao clicar no botão "Ver Gráfico", ocultar relatório e mostrar o devido gráfico
- [x] Ao clicar no botão "Ver Gráfico", mudar botão para "Ver Relatório"
- [x] Poder realizar um filtro no gráfico por fluxo, status, e ou período (data x à data y)
- [x] Poder visualizar corretamente o gráfico filtrado
- [x] Ao clicar no botão "Ver Relatório", ocultar gráfico e mostrar o devido relatório
- [x] Ao clicar no botão "Ver Relatório", mudar botão para "Ver Gráfico"
- [x] Ao clicar no botão "Ver Gráfico", caso esteja sendo filtrando por períodos maiores do que 2 anos a partir do mês atual, informar "Não é possível gerar gráfico com períodos superiores a 2 anos"

## Capturas de Telas (Protótipo)

**Estatísticas da quantidade de processos concluídos / interrompidos ao ser aberto pela primeira vez trazendo relatório geral:**
![Imagem](https://i.imgur.com/5IGD51F.png)
**Relatório ao ser filtrado:**
![Imagem](https://i.imgur.com/0pGyw0H.png)
**Ao clicar no botão "Ver Gráfico" mostrando gráfico filtrado:**
![Imagem](https://i.imgur.com/MmuLIHV.png)
**Realizando um novo filtro na página do gráfico:**
![Imagem](https://i.imgur.com/ezDV3Rc.png)
**Gráfico sendo mostrado sem filtro de status:**
![Imagem](https://i.imgur.com/T5Yb2Bt.png)

**Comment by well1981** [comment]
Alterar o nome da US02: Estatística da quantidade de processos concluídos E FINALIZADOS por fluxo. Lembrando que concluído é quando percorreu todo o fluxo e finalizado é quando encerrou antes da última etapa. Solicitei na US01 que o gráfico dessa estatística fosse retirado de lá (cada gráfico na sua estatística). Alterar o critério de aceitação: Gráfico mostrando a quantidade de processos concluídos E FINALIZADOS de cada fluxo.

**Comment by well1981** [comment]
A estatística na aba Unidades deve ficar na aba Estatísticas (concentrar tudo lá). Não utilizar processos "encerrados" (ver gráfico em Unidades), pois o correto é "finalizados". Trocar o campo "ano" por "período" (xx/xx/xx a xx/xx/xx).

**Comment by well1981** [comment]
- atualizar todos os textos da US com os nomes definidos (interrompido e concluído)
- o título do relatório pode ser apenas "Visualizar quantidade de processos concluídos / interrompidos"
- deve ser possível não preencher a data; nesse caso, o relatório informaria todo o período (iniciando com a criação do fluxo); não foi possível gerar gráfico sem o preenchimento da data
- os botões ver gráfico e ver relatório poderiam ficar um ao lado do outro
- não foi possível baixar o relatório em PDF ou outro tipo de arquivo

**Comment by well1981** [comment]
![image](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/assets/121133676/99b8a148-d61d-4651-bde8-08f6eaf94e7e)

**Comment by well1981** [comment]
Critérios de aceitação validados.

**Comment by well1981** [comment]
Implementação validada.
