### ISSUE TITLE
US05 - Baixar Relatório em Formato PDF e EXCEL

### ISSUE THREAD

**Issue by M0tt1nh4** [fga-eps-mds/2023-2-CAPJu-Doc#23]
## Descrição da História
Eu, como estagiário, servidor, diretor, juiz, e administrador, gostaria de baixar um relatório em formato EXCEL e pdf para ter a flexibilidade de compartilhar e armazenar os dados de maneira mais conveniente e acessível.

## Tasks
As seguintes tasks, devem ser completadas para concluir a história:   
- [ ] Alinhar protótipo com o P.O
- [ ] Criar mecanismo que exporte o relatório selecionado para EXCEL
- [ ] Criar mecanismo que exporte o relatório selecionado para PDF

## Critérios de Aceitação
- **Relatório de "Visualizar Processos na etapa de um fluxo"**

    _No Formato de Gráfico: (Selecionando somente o fluxo)_
    - [ ] Baixar um PDF.

    _No Formato de Tabela: (Selecionando Fluxo e Etapa)_
    - [ ] Baixar PDF;
    - [ ] Baixar EXCEL.

-  **Relatório de "Visualizar Tempo Médio de Conclusão dos Processos por Etapa"**
   - [ ] Baixar PDF;
   - [ ] Baixar PDF;

 - **Relatório de "Visualizar relatório com a quantidade de processos concluídos ou finalizados"**
        
    _No Formato de Gráfico:_
   - [ ] Baixar um PDF.

    _No Formato de Tabela:_
   - [ ] Baixar PDF;
   - [ ] Baixar EXCEL.

  - **Relatório de "Visualizar Processos com filtro de data de vencimento"**
 
    - [ ] Baixar PDF;
    - [ ] Baixar EXCEL.

- **Relatório de "Processos notificados com tempo excedido"**
    - [ ] Baixar PDF;
    - [ ] Baixar EXCEL.

## Capturas de Tela (Protótipo)

![image](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/assets/43673797/861ac41b-7b45-4889-a405-985a5e943bb4)

![image](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/assets/43673797/b2989ed0-9724-42d0-9829-d0ec4b63537a)

**Comment by well1981** [comment]
Sem observações. Perfeita a US!

**Comment by well1981** [comment]
Está correto. Pode prosseguir.

**Comment by well1981** [comment]
Essa opção aparece apenas no relatório "visualizar processos filtrados por data de vencimento". Mas ao clicar nos dois tipos de download (PDF e CSV) não funcionou. ESSA FUNCIONALIDADE DEVE ESTAR DISPONÍVEL EM TODOS OS RELATÓRIOS (ver comentário na US).

**Comment by well1981** [comment]
Válido os critérios de aceitação.
