### ISSUE TITLE
US03 - Visualizar relatório do processo

### ISSUE THREAD

**Issue by DanielRogs** [fga-eps-mds/2023-2-CAPJu-Doc#25]
## Descrição da História
Eu, como usuário, gostaria de ter a capacidade de visualizar as informações detalhadas sobre um processo específico para poder avaliar o processo em profundidade, entender seu status atual e fazer melhorias informadas com base nos dados.

## Tasks
As seguintes tasks  devem ser completas para concluir a história:
- [x] Alinhar para saber quais dados são necessários exibir sobre o processo
- [ ] Como vão ser pegos os dados
- [ ] Criação do protótipo
- [ ] Validação de protótipo com o P.O.
- [ ] Desenvolvimento da exibição dos dados contidos no processo
- [ ] Desenvolvimento da exibição do histórico de alterações e status do processo

## Critérios de Aceitação
Seção para os critérios que definem acerca da aceitação da tarefa. 
- [ ] Mostrar apenas os dados processo que foi selecionado
- [ ] Visualizar relatório com os novos campos criados nas US03, US06 e US04.
- [ ] Mostrar todas as informações do relatório (fluxos, etapas, histórico das etapas, tempo em cada etapa + informações pertinentes do processo).

## Capturas de Telas (Protótipo)
![Imagem2](https://media.discordapp.net/attachments/750707734910992535/1162130003631284305/Processos_Pt.2_V2.png?ex=653ad0e8&is=65285be8&hm=16b41108f501f717dc33dbb8ff4f21563ac1413012eec2e798a1616abda788ef&=&width=419&height=616)

**Comment by Denniel-sudo** [comment]
Depende da [US01](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/issues/14)

**Comment by well1981** [comment]
Nesse caso, não se trata de uma estatística, mas de visualização das informações do processo. Embora o print da tela não esteja na US, consegui visualizar no Figma. Não ficou claro como eu chegaria na tela do protótipo (clicando no processo, por exemplo?).

**Comment by JongaMatos** [comment]
Issue Duplicada, olhar US 06
