### ISSUE TITLE
US04 - Visualizar o tempo de conclusão dos processos por Etapa

### ISSUE THREAD

**Issue by DanielRogs** [fga-eps-mds/2023-2-CAPJu-Doc#31]
## Descrição da História
Eu, como usuário, gostaria de ter a capacidade de visualizar o tempo que cada etapa levou para ser concluída em um processo, para poder ter as estatísticas do tempo gasto ou atrasos nessas etapas.

## Tasks
As seguintes tasks  devem ser completas para concluir a história:
- [x] Construir no protótipo
- [x] Preparar o banco para receber o dia que os processos foram movidos/iniciados na etapa
- [x] Sistema de cálculo de diferença do dia atual com o dia do início
- [x] Implementar no gráfico

## Critérios de Aceitação
Seção para os critérios que definem acerca da aceitação da tarefa. 
- [x] Poder expandir o campo de estatísticas com título "Visualizar tempo médio de conclusão de etapa"
- [x] Poder visualizar e selecionar uma opção no campo de fluxo 
- [x] Ao clicar para prosseguir, conseguir ver o gráfico que exibe o tempo previsto X médio de conclusão de cada etapa do fluxo selecionado

## Capturas de Telas

Na página das estatísticas:

![Frame1](https://i.imgur.com/BrS6Wgp.png)
![Frame2](https://i.imgur.com/9XsnrqV.png)
![Frame3](https://imgur.com/OPNZ6Ui.png)

**Comment by well1981** [comment]
Não misturar as US01 e US02 com a US03 como feito nesta US. As duas primeiras são de estatística e a última de informações. Esta US04 precisa ser adaptada para ficar igual as duas primeiras US (US01 e US02).

**Comment by Denniel-sudo** [comment]
> Não misturar as US01 e US02 com a US03 como feito nesta US. As duas primeiras são de estatística e a última de informações. Esta US04 precisa ser adaptada para ficar igual as duas primeiras US (US01 e US02).

Não consegui entender quais aspectos dessa história gostaria que estivesse mais adaptado igual as duas primeiras, se puder detalhar um pouco mais pfv.

**Comment by well1981** [comment]
@Denniel-sudo 
Exemplo:
Fluxo TESTE
![image](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/assets/121133676/50aa4064-b41d-4eeb-91dd-1b406288abcc)

**Comment by well1981** [comment]
Eu acredito que o eixo Y seja o tempo médio gasto (tempo de conclusão da tabela acima). Faltou relacionar com o tempo previsto da tarefa, conforme indicado acima. Isso pode ser feito no gráfico com a indicação do tempo ou passando uma linha com essa informação.

**Comment by well1981** [comment]
Essa estatística não aparece:
![image](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/assets/121133676/95939ca9-6052-447e-b204-987fe15c4cbd)

**Comment by well1981** [comment]
Implementação validada.
