### ISSUE TITLE
[Feature] - Executar seed e migrations automaticamente

### ISSUE THREAD

**Issue by Denniel-sudo** [fga-eps-mds/2023-2-CAPJu-Doc#52]
## **Descreva sua issue**
Ao criar a build do projeto as migrations e as seeders devem ser executadas automaticamente.

## **Tasks**
- [ ] Criar entrypoint de todos os repositórios
- [ ] Reestruturar Dockerfile e Docker-compose de todos os repositórios

## **Critérios de Aceitação**

- [ ] O projeto deve rodar as seeders e as migrations quando buildar pela primeira vez
