### ISSUE TITLE
US10 - Exclusão de fluxo

### ISSUE THREAD

**Issue by WashingtonBispo** [fga-eps-mds/2023-2-CAPJu-Doc#6]
## Descrição da História
Eu, como servidor, diretor ou administrador. Gostaria de excluir um fluxo e todos os processos inclusos nele para poder não deixar processos acumulados ou avulsos sem fazer parte de um fluxo.

## Tasks
- [ ] Criar uma maneira de excluir um fluxo e todos os processos relacionados ao mesmo. 

## Critérios de Aceitação 
- [x] Visualizar o botão de exclusão de fluxo e poder acioná-lo
- [x] Visualizar o aviso sobre a exclusão de processos que utilizam aquele fluxo
- [x] Confirmar a exclusão e verificar que o fluxo foi excluído
- [x] Verificar se os processos que utilizavam aquele fluxo também foram excluídos
- [x] Caso exista um mesmo processo em dois fluxos. Excluir somente o do fluxo correspondente e não ambos.

![image](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/assets/48032705/f1ce19c1-a092-4dc0-be15-9bd6c0b83415)
![image](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/assets/48032705/803616e9-2923-4f3f-ab71-500c9bcdb3d8)
![image](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/assets/48032705/31de299d-167d-4276-8ebc-2c0fff87947b)

**Comment by well1981** [comment]
- não consegui visualizar as duas primeiras imagens; segue o erro:
![image](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/assets/121133676/54751a20-ab33-44dc-9d3c-e1fc7a86f91a)

**Comment by brendavsantos** [comment]
Ajustadas! Pode reavaliar por favor?

**Comment by well1981** [comment]
"Todos os processos criados a partir dele também serão deletados": um processo não é criado a partir de um fluxo; o processo é criado e inserido em um fluxo; eu posso inserir um processo em mais de um fluxo; se eu excluir um fluxo, o processo será excluído (retirado) desse fluxo, mas não do outro; não tenho certeza se vocês disseram isso com essa frase; de todo modo, é preciso verificar se isso que mencionei está ocorrendo.

**Comment by well1981** [comment]
Critérios de aceitação validados.

**Comment by well1981** [comment]
Implementação validada.
