### ISSUE TITLE
US11 - Filtrar Processo individualmente e por Etapa

### ISSUE THREAD

**Issue by M0tt1nh4** [fga-eps-mds/2023-2-CAPJu-Doc#7]
## Descrição da História
Eu, como estagiário, servidor, diretor, juiz, e administrador, gostaria de filtrar os processos por meio das Etapas para poder visualizar quais processos se encontram em uma mesma Etapa.

## Tasks
As seguintes tasks, devem ser completadas para concluir a história:   
- [ ] [Filtrar os processos exibindo apenas os que estão dentro de uma etapa](https://github.com/fga-eps-mds/)

## Critérios de Aceitação
- [x] Poder visualizar um campo de busca com seleções
- [x] Ao clicar no filtro escolhido, poder ver, entre as opções, "Etapa"
- [x] Poder selecionar uma das opções e fazer uma busca a partir dela
- [x] Obter o resultado de quais processos estão em determinado Etapa

![image](https://media.discordapp.net/attachments/1144345999553351710/1172280356477616188/image.png?ex=655fbe28&is=654d4928&hm=b5b3d020b16ffb6a090d0a214990ba07ae1cc90f9fbca24ab39ef25ac83b0aa0&=&width=938&height=618)

![image](https://media.discordapp.net/attachments/1144345999553351710/1172280645024764014/image.png?ex=655fbe6d&is=654d496d&hm=0dd1d2ca6c8142959ce5c8e3f6d806629e067448cc4c2c5b4056450a685d7f37&=&width=938&height=618)

**Comment by well1981** [comment]
- a pesquisa do fluxo na aba processo faz sentido
- a pesquisa da etapa na aba processo só fará sentido, se mostrado o fluxo junto (pode haver etapas com o mesmo nome em fluxos diferentes)

**Comment by brendavsantos** [comment]
Foi um erro de localização, mas já reorganizamos do jeito que foi pensado. O buscador é pra ser "universal" e a ideia é que fique  disponível em qualquer tela junto com os elementos do header, assim, futuramente (e conforme necessário) a equipe do seu órgão pode colocar mais opções de filtro na busca alem de "fluxo" e "etapa". O exemplo foi baseado em buscas como a do [olx](https://www.olx.com.br/), como na imagem: 

![image](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/assets/48032705/dfdb97d3-510e-4b52-8ea1-185c8eae383e)

O que acha da ideia? Assim, não precisaria ter vários campos de busca diferentes em cada tela, como era feito na versão anterior.

**Comment by well1981** [comment]
Pode ser dessa forma. Registro apenas que precisaremos testar as pesquisas para sabermos quais resultados estarão sendo apresentados.

**Comment by well1981** [comment]
Novos critérios de aceitação validados.

**Comment by well1981** [comment]
O sistema não pesquisa quando digita o termo de pesquisa e depois altera o critério de pesquisa. Favor ajustar, inclusive, se possível, que a busca desconsidere letras maiúsculas e minúsculas, bem como caracteres especiais.

**Comment by well1981** [comment]
Validada a implementação.
