### ISSUE TITLE
US15 - Feedback de Erro

### ISSUE THREAD

**Issue by JongaMatos** [fga-eps-mds/2023-2-CAPJu-Doc#8]
## **Descrição da história**

Eu, como usuário, gostaria de receber feedbacks significativos de erros, para conseguir entendê-los e se possível, contorná-los.

## **Tasks**

As seguintes tasks devem ser completas para concluir a história:

- [x] Mapear os erros que estão sendo encaminhados para o usuário.
- [x] Averiguar quais precisam ser alterados para obter maior significância para o usuário.
- [x] Implementar as mudanças.

## **Mapeamento de Erros**

| Erro | Status |
|  :---- |  :----:   |
|  Ao logar com credenciais inválidas, é retornado feedback de erro "Erro no login" | Corrigido |
|  Ao tentar criar uma conta com CPF já cadastrado é retornado o feedback de erro "Erro ao criar usuário"  |  Corrigido  |
|  Ao tentar recuperar senha é mostrado ao usuário um feedback de erro incoerente  |  Corrigido  |
|  Não é retornado erro ao criar ou editar unidade com nome já existente  |  Corrigido  |
|  Ao tentar criar uma etapa com nome já existente, é retornado "Something went wrong"  |  Corrigido  |
|  Não é retornado feedback de erro ao criar ou editar fluxo com nome já existente  |  Corrigido  |
|  Ao avançar um processo com mesmo número de registro e etapa o erro "SequelizeUniqueConstraintError: Validation error" é mostrado |  Corrigido  |
|  No relatório "Visualizar tempo médio de cada etapa" não é retornado feedback de erro ao não selecionar fluxo e clicar no botão "confirmar"  |  Corrigido |
|  No relatório "Visualizar quantidade de processos em cada etapa" não é retornado feedback de erro ao não selecionar etapa e clicar no botão "confirmar"  |  Corrigido  |
|  No relatório "Visualizar processos filtrados por data de vencimento", ao selecionar uma data inicial maior do que uma data final é retornado o feedback de erro "Por favor, insira uma data maior que a outra"  |  Corrigido  |

## **Critérios de Aceitação**
- [ ] Ao inserir um CPF inválido, na tela de login, deve retornar o feedback de erro "Usuário inexistente. Por favor, verifique o CPF inserido."
- [ ] Ao inserir uma senha inválida, na tela de login, deve retornar o feedback de erro "Senha incorreta."
- [ ] Ao tentar criar uma conta com CPF já cadastrado deve retornar o feedback de erro "CPF já cadastrado."
- [ ] Ao tentar recuperar uma senha com e-mail inválido, na tela de recuperação de senha, deve retornar o feedback de erro "E-mail não encontrado. Por favor, insira um e-mail válido."
- [ ] Ao tentar recuperar uma senha com sucesso, na tela de recuperação de senha, deve retornar o feedback de sucesso  "Instruções para recuperação de senha enviadas com sucesso para o e-mail fornecido."
- [ ] Ao tentar criar uma unidade com nome já existente de retornar o feedback de erro "Nome da unidade já existe. Por favor, escolha um nome diferente."
- [ ] Ao tentar editar uma unidade com nome já existente de retornar o feedback de erro "Nome da unidade já existe. Por favor, escolha um nome diferente."
- [ ] Ao tentar criar uma etapa com nome já existente, na unidade, retornar o feedback de erro "Etapa com mesmo nome já existe na unidade. Por favor, escolha um nome diferente."
- [ ] Ao tentar editar uma etapa com nome já existente, na unidade, retornar o feedback de erro "Etapa com mesmo nome já existe na unidade. Por favor, escolha um nome diferente."
- [ ] Ao tentar criar um fluxo com nome já existente deve retornar o feedback de erro "Nome do fluxo já existe. Por favor, escolha um nome diferente."
- [ ] Ao tentar editar um fluxo com nome já existente deve retornar o feedback de erro "Nome do fluxo já existe. Por favor, escolha um nome diferente."
- [ ] No relatório "Visualizar tempo médio de cada etapa" deve retornar feedback de erro "Selecione um fluxo antes de confirmar."  ao não selecionar fluxo e clicar no botão "confirmar" 
- [ ] No relatório "Visualizar quantidade de processos em cada etapa" deve retornar feedback de erro "Selecione uma etapa antes de confirmar." ao não selecionar etapa e clicar no botão "confirmar"
- [ ] No relatório "Visualizar processos filtrados por data de vencimento", ao selecionar uma data inicial maior do que uma data final, deve retornar o feedback de erro "A data de início deve ser anterior à data de fim. Por favor, ajuste as datas e tente novamente."

**Comment by well1981** [comment]
Validados os critérios de aceitação.

**Comment by well1981** [comment]
Validada a implementação.
