### ISSUE TITLE
US19 - Autenticar rotas

### ISSUE THREAD

**Issue by brendavsantos** [fga-eps-mds/2023-2-CAPJu-Doc#9]
## Descrição da História
Eu, como usuário, gostaria de ter as rotas de páginas privadas autenticadas para poder garantir a segurança e a privacidade dos dados e dos processos, onde somente usuários autorizados teriam acesso às páginas restritas. 

## Tasks
As seguintes tasks  devem ser completas para concluir a história:
- [ ] [Definir método de autenticação](https://github.com/fga-eps-mds/)
- [ ] [Verificar se o usuário tem as permissões necessárias antes de enviar requisições](https://github.com/fga-eps-mds/)

## Critérios de Aceitação
Seção para os critérios que definem acerca da aceitação da tarefa. 
- [ ] Descrever o critério de aceitação 
- [ ]

**Comment by well1981** [comment]
Validada a implementação.
